apiVersion: v1
kind: Namespace
metadata:
  name: konga
---

apiVersion: v1
kind: Secret
metadata:
  name: pg-creds
  namespace: konga
type: Opaque
data:
  POSTGRES_DB: konga
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin123
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: konga
  namespace: konga
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: konga
        app: konga
    spec:
      containers:
      - name: konga
        image: pantsel/konga
        env:
        - name: DB_ADAPTER
          value: postgres
        - name: DB_HOST
          value: postgres
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: pg-creds
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-creds
              key: POSTGRES_PASSWORD
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: pg-creds
              key: POSTGRES_DB
        ports:
        - containerPort: 1337
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: konga
  name: konga-svc
  namespace: konga
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 1337
  selector:
    app: konga
---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: konga
  namespace: konga
spec:
  rules:
  - host: konga.example.com
    http:
      paths:
      - backend:
          serviceName: konga-svc
          servicePort: 443
        path: /
  tls:
    - hosts:
      - konga.example.com
      secretName: certificate-secret

---