apiVersion: v1
kind: Namespace
metadata:
  name: konga
---

apiVersion: v1
kind: Secret
metadata:
  name: pg-creds
  namespace: konga
type: Opaque
data:
  POSTGRES_DB: konga
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin123
---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  namespace: konga
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/datastore/db-data"
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  namespace: konga
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: konga
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:9.6
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: pg-creds
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: konga
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres